// Generated by Claude (Anthropic).

#ifndef YUM_STEAM_API_INCLUDED
#define YUM_STEAM_API_INCLUDED

// A minimal binding to the Steam client, loaded at runtime.
//
// This deliberately does NOT use the Steamworks SDK. Two reasons:
//
//  1. The SDK cannot be redistributed in a public repository, so linking it
//     would mean every contributor had to fetch it before the tree would
//     build. Loading the library by name instead keeps the build exactly as
//     it was for anyone who does not care about Steam.
//
//  2. minorGems/game/steamGate/client/howToBuild.txt notes that Steamworks
//     "seems to be impossible when building with MinGW", which is why the
//     vanilla steamGateClient.exe is built with MSVC. The reason is that the
//     SDK's C++ interfaces are called through vtables laid out by MSVC, and
//     MinGW orders overloaded virtuals differently. Everything below goes
//     through Steam's flat C API instead (SteamAPI_ISteamUser_* and friends),
//     which is plain exported C functions with no vtable involved, so it
//     behaves the same under MinGW, GCC and Clang.
//
// Every entry point here fails softly. If Steam is not installed, not
// running, not logged in, or the library is missing, init returns false and
// the caller carries on without Steam.


// Loads the Steam library and connects to the running Steam client.
//
// inAppID is the app whose identity we claim. Steam resolves this from the
// SteamAppId environment variable when Steam launched us, and otherwise from
// steam_appid.txt in the working directory -- which is what lets this work
// when the player starts the mod directly, with Steam merely running in the
// background. If that file is absent it is written with inAppID.
//
// Returns true if the API came up and the user is logged in.
char steamAPI_init( int inAppID );


// Disconnects from Steam and unloads the library. Safe to call if init failed.
void steamAPI_shutdown();


// Pumps Steam's internal message queue. Steam does its work in response to
// this, so it must be called repeatedly while waiting on anything.
void steamAPI_runCallbacks();


// The logged-in user's 64-bit Steam ID, or 0 if unavailable.
unsigned long long steamAPI_getSteamID();


// Fills outTicket with an authentication session ticket for the app ID
// passed to steamAPI_init, and returns its length in bytes, or 0 on failure.
//
// The ticket bytes come back immediately, but Steam has to register the
// ticket with its own back end before a web API call can validate it. There
// is no way to observe that completing without the SDK's C++ callback
// machinery, so callers should pump steamAPI_runCallbacks() for a moment and
// be prepared to retry the validating call. See steamCredentials.cpp.
unsigned int steamAPI_getAuthSessionTicket( unsigned char *outTicket,
                                            int inMaxLength );


#endif
