// Generated by Claude (Anthropic).

#include "steamCredentials.h"
#include "steamAPI.h"

#include "minorGems/crypto/cryptoRandom.h"
#include "minorGems/crypto/keyExchange/curve25519.h"
#include "minorGems/formats/encodingUtils.h"
#include "minorGems/io/file/File.h"
#include "minorGems/network/web/WebRequest.h"
#include "minorGems/system/Thread.h"
#include "minorGems/system/Time.h"
#include "minorGems/util/SettingsManager.h"
#include "minorGems/util/SimpleVector.h"
#include "minorGems/util/log/AppLog.h"
#include "minorGems/util/stringUtils.h"

#include <string.h>


extern char isAHAP;


// The Steam apps these accounts are checked against. The gate server asks
// Valve whether the user owns the app before it will hand out an account,
// using a publisher key only Jason has, so these have to be the real store
// entries and the requests have to go to his server.
#define OHOL_STEAM_APP_ID 595690
#define AHAP_STEAM_APP_ID 2787060

#define OHOL_GATE_URL "http://onehouronelife.com/steamGate/server.php"
#define AHAP_GATE_URL "http://onehouronelife.com/ahapSteamGate/server.php"

// Steam auth tickets run to a few hundred bytes; the same headroom vanilla
// gives them.
#define MAX_TICKET_BYTES 2048

// A ticket ID is 23 characters, and the shared secret it is XORed against is
// 32 bytes. Anything longer than the key would run off the end of it.
#define MAX_ACCOUNT_KEY_BYTES 32

#define WEB_TIMEOUT_SECONDS 20.0

// Steam hands over the ticket bytes before its back end has finished
// registering the ticket, and without the SDK's C++ callbacks there is no
// way to watch for that finishing. So pump Steam for a moment first, and if
// the server still says the ticket is no good, wait and ask again.
// Steam will report itself initialised and the user logged on while it is
// still finishing its own handshake with Valve, and in that window it hands
// out no tickets at all. Anyone who starts Steam and the mod together lands
// in it, so wait a little rather than failing outright -- but not long, since
// the player is sitting in front of a frozen settings page and can press the
// button again.
#define TICKET_WAIT_SECONDS 10.0
#define TICKET_POLL_SECONDS 1.0

#define TICKET_WARMUP_SECONDS 2.0
#define TICKET_RETRY_COUNT 3
#define TICKET_RETRY_SECONDS 3.0



static int getAppID() {
    File appIDFile( NULL, "steam_appid.txt" );

    if( appIDFile.exists() ) {
        int existingID = appIDFile.readFileIntContents( 0 );

        if( existingID > 0 ) {
            return existingID;
        }
    }

    if( isAHAP ) {
        return AHAP_STEAM_APP_ID;
    }

    return OHOL_STEAM_APP_ID;
}



static char *getGateURL() {
    // A Steam install of the base game already has this file: the depot
    // build script writes it next to the game. Prefer it, so that if Jason
    // ever moves the endpoint we follow along without a mod release.
    File urlFile( NULL, "steamGateServerURL.txt" );

    if( urlFile.exists() ) {
        char *url = urlFile.readFileContents();

        if( url != NULL ) {
            char *trimmed = trimWhitespace( url );
            delete [] url;

            if( strstr( trimmed, "http" ) == trimmed ) {
                return trimmed;
            }

            delete [] trimmed;
        }
    }

    if( isAHAP ) {
        return stringDuplicate( AHAP_GATE_URL );
    }

    return stringDuplicate( OHOL_GATE_URL );
}



// Runs one request to completion, keeping Steam pumped while it waits.
// Returns the response body, or NULL.
static char *runWebRequest( const char *inURL ) {
    WebRequest request( "GET", inURL, NULL, NULL, WEB_TIMEOUT_SECONDS );

    while( true ) {
        int status = request.step();

        if( status == 1 ) {
            return request.getResult();
        }

        if( status == -1 ) {
            AppLog::error( "Steam: the steamGate request failed or timed "
                           "out." );
            return NULL;
        }

        steamAPI_runCallbacks();
        Thread::staticSleep( 50 );
    }
}



// Blocks for inSeconds, letting Steam get on with its work.
static void pumpSteam( double inSeconds ) {
    double startTime = Time::getCurrentTime();

    while( Time::getCurrentTime() - startTime < inSeconds ) {
        steamAPI_runCallbacks();
        Thread::staticSleep( 50 );
    }
}



// Asks Steam for a ticket until it produces one or we run out of patience.
static unsigned int getAuthTicket( unsigned char *outTicket,
                                   int inMaxLength ) {
    double startTime = Time::getCurrentTime();
    char waited = false;

    while( true ) {
        unsigned int ticketLength =
            steamAPI_getAuthSessionTicket( outTicket, inMaxLength );

        if( ticketLength > 0 ) {
            AppLog::infoF( "Steam: got a %u-byte auth ticket.", ticketLength );
            return ticketLength;
        }

        if( Time::getCurrentTime() - startTime > TICKET_WAIT_SECONDS ) {
            AppLog::error( "Steam: Steam never issued an authentication "
                           "ticket. It may still have been connecting." );
            return 0;
        }

        if( ! waited ) {
            AppLog::info( "Steam: no ticket yet, waiting for Steam to finish "
                          "connecting." );
            waited = true;
        }

        pumpSteam( TICKET_POLL_SECONDS );
    }
}



// True if the server's answer means "ask again in a moment" rather than
// "no". The gate server reports an unregistered ticket as
// "FAILED: Bad Steam session ticket"; everything else it refuses for is a
// real refusal, like not owning the app.
static char isTicketNotReady( const char *inResponse ) {
    return strstr( inResponse, "FAILED" ) != NULL &&
           strstr( inResponse, "ticket" ) != NULL;
}



// A key is 23 characters of readable base32 in hyphenated groups. Just check
// that what came out of the XOR is plausible text, so that a botched key
// exchange is not written into the settings as if it were an account.
static char looksLikeAccountKey( const char *inKey ) {
    int length = strlen( inKey );

    if( length < 5 ) {
        return false;
    }

    for( int i=0; i<length; i++ ) {
        char c = inKey[i];

        if( c != '-' &&
            !( c >= '0' && c <= '9' ) &&
            !( c >= 'A' && c <= 'Z' ) &&
            !( c >= 'a' && c <= 'z' ) ) {
            return false;
        }
    }

    return true;
}



// Everything from the auth ticket to the saved settings. Split out from
// fetchSteamCredentials so that the Steam connection is shut down in exactly
// one place.
static char runGateProtocol() {
    unsigned char ticketData[ MAX_TICKET_BYTES ];

    unsigned int ticketLength = getAuthTicket( ticketData,
                                               MAX_TICKET_BYTES );

    if( ticketLength == 0 ) {
        return false;
    }

    // Our half of the key exchange. The server generates a fresh key pair per
    // request, so this secret protects exactly one reply.
    unsigned char ourSecretKey[32];
    unsigned char ourPublicKey[32];

    if( ! getCryptoRandomBytes( ourSecretKey, 32 ) ) {
        AppLog::error( "Steam: could not get secure random bytes for the key "
                       "exchange." );
        return false;
    }

    curve25519_genPublicKey( ourPublicKey, ourSecretKey );

    char *ticketHex = hexEncode( ticketData, ticketLength );
    char *publicKeyHex = hexEncode( ourPublicKey, 32 );
    char *gateURL = getGateURL();

    char *url = autoSprintf( "%s?action=get_account"
                             "&auth_session_ticket=%s"
                             "&client_public_key=%s",
                             gateURL, ticketHex, publicKeyHex );

    // Not logged: the ticket is a credential in its own right, and the
    // vanilla client writing it into a plaintext log next to the game is not
    // a habit worth copying.
    AppLog::infoF( "Steam: asking %s for an account.", gateURL );

    delete [] gateURL;
    delete [] ticketHex;
    delete [] publicKeyHex;

    pumpSteam( TICKET_WARMUP_SECONDS );

    char *response = NULL;

    for( int attempt=0; attempt<TICKET_RETRY_COUNT; attempt++ ) {
        if( attempt > 0 ) {
            AppLog::info( "Steam: the ticket was not registered yet, "
                          "waiting to try again." );
            pumpSteam( TICKET_RETRY_SECONDS );
        }

        response = runWebRequest( url );

        if( response == NULL ) {
            break;
        }

        if( ! isTicketNotReady( response ) ) {
            break;
        }

        delete [] response;
        response = NULL;
    }

    delete [] url;

    if( response == NULL ) {
        return false;
    }

    SimpleVector<char *> *tokens = tokenizeString( response );

    // server_public_key, email, encrypted_ticket_id
    if( tokens->size() != 3 ||
        strlen( *( tokens->getElement( 0 ) ) ) != 64 ) {

        AppLog::errorF( "Steam: the steamGate server refused us: %s",
                        response );

        for( int i=0; i<tokens->size(); i++ ) {
            delete [] *( tokens->getElement( i ) );
        }
        delete tokens;
        delete [] response;
        return false;
    }

    delete [] response;

    char *serverPublicKeyHex = *( tokens->getElement( 0 ) );
    char *email = *( tokens->getElement( 1 ) );
    char *encryptedKeyHex = *( tokens->getElement( 2 ) );
    delete tokens;

    char success = false;

    unsigned char *serverPublicKey = hexDecode( serverPublicKeyHex );
    unsigned char *encryptedKey = hexDecode( encryptedKeyHex );
    int encryptedKeyLength = strlen( encryptedKeyHex ) / 2;

    if( serverPublicKey == NULL || encryptedKey == NULL ||
        encryptedKeyLength < 1 ||
        encryptedKeyLength > MAX_ACCOUNT_KEY_BYTES ) {

        AppLog::error( "Steam: the steamGate server sent a malformed reply." );
    }
    else {
        unsigned char sharedSecretKey[32];

        curve25519_genSharedSecretKey( sharedSecretKey, ourSecretKey,
                                       serverPublicKey );

        char *accountKey = new char[ encryptedKeyLength + 1 ];

        for( int i=0; i<encryptedKeyLength; i++ ) {
            accountKey[i] = encryptedKey[i] ^ sharedSecretKey[i];
        }
        accountKey[ encryptedKeyLength ] = '\0';

        if( looksLikeAccountKey( accountKey ) && strstr( email, "@" ) != NULL ) {
            SettingsManager::setSetting( "email", email );
            SettingsManager::setSetting( "accountKey", accountKey );

            AppLog::infoF( "Steam: set up the account for %s.", email );
            success = true;
        }
        else {
            AppLog::error( "Steam: the account key did not decrypt cleanly, "
                           "discarding it." );
        }

        // Never logged, and gone from memory as soon as it is saved.
        memset( accountKey, 0, encryptedKeyLength );
        delete [] accountKey;
        memset( sharedSecretKey, 0, 32 );
    }

    if( serverPublicKey != NULL ) {
        delete [] serverPublicKey;
    }
    if( encryptedKey != NULL ) {
        delete [] encryptedKey;
    }

    delete [] serverPublicKeyHex;
    delete [] email;
    delete [] encryptedKeyHex;

    memset( ourSecretKey, 0, 32 );

    return success;
}



char fetchSteamCredentials() {
    int appID = getAppID();

    AppLog::infoF( "Steam: asked for an account, setting one up through "
                   "Steam as app %d.", appID );

    if( ! steamAPI_init( appID ) ) {
        return false;
    }

    char success = runGateProtocol();

    steamAPI_shutdown();

    if( ! success ) {
        AppLog::info( "Steam: could not set up an account, leaving the saved "
                      "one alone." );
    }

    return success;
}
