// Generated by Claude (Anthropic).

#include "steamAPI.h"

#include "minorGems/util/log/AppLog.h"
#include "minorGems/util/stringUtils.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>


#ifdef WIN32
    #include <windows.h>
    // S_CALLTYPE in the Steamworks headers. MinGW defaults to __cdecl for
    // free functions anyway, but say so rather than depend on the default.
    #define YUM_STEAM_CALL __cdecl
#else
    #include <dlfcn.h>
    #define YUM_STEAM_CALL
#endif

#ifdef __mac__
    #include <mach-o/dyld.h>
#endif

#include "minorGems/util/SimpleVector.h"


// Steam's flat API. Every one of these is an exported C function -- no
// vtables -- which is what makes this safe to call from a MinGW build.
// "char" stands in for the SDK's bool: both are a single byte here.
typedef char (YUM_STEAM_CALL *fnInit)();

// SDK 1.57 stopped exporting SteamAPI_Init -- it became an inline header
// function -- and offers this to bindings that are not using the headers.
// Writes into a 1024-byte buffer and returns 0 for success.
typedef int (YUM_STEAM_CALL *fnInitFlat)( char *outErrorMessage );

typedef void (YUM_STEAM_CALL *fnShutdown)();
typedef void (YUM_STEAM_CALL *fnRunCallbacks)();
typedef int (YUM_STEAM_CALL *fnGetHSteamUser)();
typedef int (YUM_STEAM_CALL *fnGetHSteamPipe)();
typedef void *(YUM_STEAM_CALL *fnCreateInterface)( const char *inVersion );
typedef void *(YUM_STEAM_CALL *fnGetISteamUser)( void *inClient,
                                                 int inHSteamUser,
                                                 int inHSteamPipe,
                                                 const char *inVersion );
// SDK 1.58 added the trailing identity argument. Declaring it here and
// passing NULL is safe against both generations: these are cdecl functions,
// so an older four-argument build simply ignores the extra one, exactly as
// it would for a varargs call.
typedef unsigned int (YUM_STEAM_CALL *fnGetAuthSessionTicket)(
    void *inUser, void *outTicket, int inMaxTicket, unsigned int *outLength,
    const void *inNetworkingIdentity );
typedef unsigned long long (YUM_STEAM_CALL *fnGetSteamID)( void *inUser );
typedef char (YUM_STEAM_CALL *fnBLoggedOn)( void *inUser );


static void *sLibHandle = NULL;
static char *sLibPath = NULL;

static fnInit sInit = NULL;
static fnInitFlat sInitFlat = NULL;
static fnShutdown sShutdown = NULL;
static fnRunCallbacks sRunCallbacks = NULL;
static fnCreateInterface sCreateInterface = NULL;
static fnGetHSteamUser sGetHSteamUser = NULL;
static fnGetHSteamPipe sGetHSteamPipe = NULL;
static fnGetISteamUser sGetISteamUser = NULL;
static fnGetAuthSessionTicket sGetAuthSessionTicket = NULL;
static fnGetSteamID sGetSteamID = NULL;
static fnBLoggedOn sBLoggedOn = NULL;

// ISteamUser, once we have talked the client into handing one over.
static void *sSteamUser = NULL;

static char sAPIStarted = false;



static void *loadSymbol( const char *inName ) {
    if( sLibHandle == NULL ) {
        return NULL;
    }

#ifdef WIN32
    return (void *)GetProcAddress( (HMODULE)sLibHandle, inName );
#else
    return dlsym( sLibHandle, inName );
#endif
}



static void closeLibrary() {
    sSteamUser = NULL;

    sInit = NULL;
    sInitFlat = NULL;
    sShutdown = NULL;
    sRunCallbacks = NULL;
    sCreateInterface = NULL;
    sGetHSteamUser = NULL;
    sGetHSteamPipe = NULL;
    sGetISteamUser = NULL;
    sGetAuthSessionTicket = NULL;
    sGetSteamID = NULL;
    sBLoggedOn = NULL;

    if( sLibHandle != NULL ) {
#ifdef WIN32
        FreeLibrary( (HMODULE)sLibHandle );
#else
        dlclose( sLibHandle );
#endif
        sLibHandle = NULL;
    }

    if( sLibPath != NULL ) {
        delete [] sLibPath;
        sLibPath = NULL;
    }
}



#ifdef __mac__

// The directory holding our own executable, which for a .app is
// YummyLife.app/Contents/MacOS. Caller owns the result.
//
// Needed because the working directory is the *game folder* the bundle was
// dropped into, not the bundle, so a library shipped inside the app is not
// reachable by any relative path.
static char *getExecutableDirectory() {
    uint32_t size = 0;

    // Asking with no buffer reports the size we need.
    _NSGetExecutablePath( NULL, &size );

    if( size == 0 ) {
        return NULL;
    }

    char *path = new char[ size + 1 ];
    path[ size ] = '\0';

    if( _NSGetExecutablePath( path, &size ) != 0 ) {
        delete [] path;
        return NULL;
    }

    char *lastSlash = strrchr( path, '/' );

    if( lastSlash == NULL ) {
        delete [] path;
        return NULL;
    }

    lastSlash[0] = '\0';

    return path;
}

#endif



// Tries each location in turn and keeps the first that loads.
//
// The working directory is the game folder by the time this runs (gameSDL.cpp
// chdirs there on startup), and a Windows Steam install of OHOL already has
// steam_api.dll sitting in it, shipped alongside the vanilla
// steamGateClient.exe. So on the platform where the base game is actually
// sold through Steam, there is nothing for the player to install.
//
// Elsewhere the library has to come from somewhere else, so a copy shipped
// inside YummyLife.app is looked for first, then one sitting loose in the
// game folder.
static char loadLibrary() {
    SimpleVector<char *> candidates;

#ifdef WIN32
    // LoadLibrary searches the folder holding the .exe as well as the
    // working directory, and both are the game folder here.
    candidates.push_back( stringDuplicate( "steam_api.dll" ) );
    candidates.push_back( stringDuplicate( "steam_api64.dll" ) );
#else

    #ifdef __mac__
        #define YUM_STEAM_LIB_NAME "libsteam_api.dylib"
    #else
        #define YUM_STEAM_LIB_NAME "libsteam_api.so"
    #endif

    #ifdef __mac__
        char *exeDir = getExecutableDirectory();

        if( exeDir != NULL ) {
            // Shipped inside the bundle, next to the Homebrew libraries
            // mac-bundle.sh puts there.
            candidates.push_back(
                autoSprintf( "%s/../Frameworks/%s", exeDir,
                             YUM_STEAM_LIB_NAME ) );

            // Or loose beside the executable, for a bare non-bundle build.
            candidates.push_back(
                autoSprintf( "%s/%s", exeDir, YUM_STEAM_LIB_NAME ) );

            delete [] exeDir;
        }
    #endif

    // Dropped into the game folder by hand.
    candidates.push_back( autoSprintf( "./%s", YUM_STEAM_LIB_NAME ) );

    // Anywhere the dynamic loader already looks.
    candidates.push_back( stringDuplicate( YUM_STEAM_LIB_NAME ) );
#endif

    for( int i=0; i<candidates.size(); i++ ) {
        char *path = candidates.getElementDirect( i );

#ifdef WIN32
        sLibHandle = (void *)LoadLibraryA( path );
#else
        sLibHandle = dlopen( path, RTLD_LAZY | RTLD_LOCAL );
#endif

        if( sLibHandle != NULL ) {
            sLibPath = stringDuplicate( path );
            AppLog::infoF( "Steam: loaded %s", path );
            break;
        }
    }

    for( int i=0; i<candidates.size(); i++ ) {
        delete [] candidates.getElementDirect( i );
    }

    if( sLibHandle != NULL ) {
        return true;
    }

    AppLog::info( "Steam: no Steam library found in the bundle or next to "
                  "the game, skipping Steam login." );
    return false;
}



// Finds the newest "<inPrefix>NNN" interface version string embedded in the
// Steam library itself.
//
// This matters more than it looks. The flat functions in the library dispatch
// through whichever version of the C++ interface that build was compiled
// against, so asking the client for a different version hands those functions
// an object with a vtable they do not expect. Rather than hardcode a version
// and hope it matches whatever steam_api library the player happens to have,
// read the answer out of the binary: a given build embeds exactly the
// versions it speaks, one per interface. The one Jason ships with OHOL, for
// instance, contains SteamClient017 and SteamUser019 and nothing else.
static char findInterfaceVersion( const char *inPrefix,
                                  char *outVersion, int inOutSize ) {
    if( sLibPath == NULL ) {
        return false;
    }

    FILE *f = fopen( sLibPath, "rb" );

    if( f == NULL ) {
        return false;
    }

    fseek( f, 0, SEEK_END );
    long fileSize = ftell( f );
    fseek( f, 0, SEEK_SET );

    // Steam's shim is a few hundred KB. Anything wildly bigger is not it.
    if( fileSize <= 0 || fileSize > 32 * 1024 * 1024 ) {
        fclose( f );
        return false;
    }

    unsigned char *data = new unsigned char[ fileSize ];
    long numRead = (long)fread( data, 1, fileSize, f );
    fclose( f );

    int prefixLength = strlen( inPrefix );
    int best = -1;

    // A version string is the prefix, three digits, then a terminator.
    for( long i=0; i + prefixLength + 4 <= numRead; i++ ) {
        if( memcmp( &( data[i] ), inPrefix, prefixLength ) != 0 ) {
            continue;
        }

        unsigned char *digits = &( data[ i + prefixLength ] );

        if( digits[0] < '0' || digits[0] > '9' ||
            digits[1] < '0' || digits[1] > '9' ||
            digits[2] < '0' || digits[2] > '9' ||
            digits[3] != '\0' ) {
            continue;
        }

        int version = ( digits[0] - '0' ) * 100 +
                      ( digits[1] - '0' ) * 10 +
                      ( digits[2] - '0' );

        if( version > best ) {
            best = version;
        }
    }

    delete [] data;

    if( best < 0 ) {
        return false;
    }

    snprintf( outVersion, inOutSize, "%s%03d", inPrefix, best );
    return true;
}



// Steam reads this out of the working directory to learn who we are when it
// was not the one that launched us. Only written if absent, so a folder that
// already has one (or that a future Steam build of the mod ships) is left
// alone.
static void writeAppIDFile( int inAppID ) {
    FILE *f = fopen( "steam_appid.txt", "r" );

    if( f != NULL ) {
        fclose( f );
        return;
    }

    f = fopen( "steam_appid.txt", "w" );

    if( f == NULL ) {
        AppLog::error( "Steam: could not write steam_appid.txt "
                       "(is the game folder read-only?)" );
        return;
    }

    fprintf( f, "%d", inAppID );
    fclose( f );

    AppLog::infoF( "Steam: wrote steam_appid.txt with app ID %d", inAppID );
}



char steamAPI_init( int inAppID ) {
    if( sAPIStarted ) {
        return true;
    }

    if( ! loadLibrary() ) {
        return false;
    }

    // Only now, once we know there is a Steam library here to talk to. A
    // player with no Steam at all should not find a new file in their game
    // folder for their trouble.
    writeAppIDFile( inAppID );

    sInit = (fnInit)loadSymbol( "SteamAPI_Init" );
    sInitFlat = (fnInitFlat)loadSymbol( "SteamAPI_InitFlat" );
    sShutdown = (fnShutdown)loadSymbol( "SteamAPI_Shutdown" );
    sRunCallbacks = (fnRunCallbacks)loadSymbol( "SteamAPI_RunCallbacks" );
    sCreateInterface =
        (fnCreateInterface)loadSymbol( "SteamInternal_CreateInterface" );
    sGetHSteamUser = (fnGetHSteamUser)loadSymbol( "SteamAPI_GetHSteamUser" );
    sGetHSteamPipe = (fnGetHSteamPipe)loadSymbol( "SteamAPI_GetHSteamPipe" );
    sGetISteamUser =
        (fnGetISteamUser)loadSymbol( "SteamAPI_ISteamClient_GetISteamUser" );
    sGetAuthSessionTicket = (fnGetAuthSessionTicket)loadSymbol(
        "SteamAPI_ISteamUser_GetAuthSessionTicket" );
    sGetSteamID =
        (fnGetSteamID)loadSymbol( "SteamAPI_ISteamUser_GetSteamID" );
    sBLoggedOn = (fnBLoggedOn)loadSymbol( "SteamAPI_ISteamUser_BLoggedOn" );

    if( ( sInit == NULL && sInitFlat == NULL ) ||
        sShutdown == NULL || sRunCallbacks == NULL ||
        sCreateInterface == NULL || sGetHSteamUser == NULL ||
        sGetHSteamPipe == NULL || sGetISteamUser == NULL ||
        sGetAuthSessionTicket == NULL || sGetSteamID == NULL ||
        sBLoggedOn == NULL ) {

        AppLog::error( "Steam: library is missing flat API functions, "
                       "skipping Steam login." );
        closeLibrary();
        return false;
    }

    // Read this before connecting, so an unusable library is rejected
    // without having bothered the Steam client at all.
    char clientVersion[64];
    char userVersion[64];

    if( ! findInterfaceVersion( "SteamClient", clientVersion,
                                sizeof( clientVersion ) ) ||
        ! findInterfaceVersion( "SteamUser", userVersion,
                                sizeof( userVersion ) ) ) {

        AppLog::error( "Steam: could not read the interface versions out of "
                       "the Steam library, skipping Steam login." );
        closeLibrary();
        return false;
    }

    AppLog::infoF( "Steam: library speaks %s and %s", clientVersion,
                   userVersion );

    // Fails when Steam is not running, nobody is logged in, or the app ID
    // could not be resolved. All ordinary situations, not errors.
    if( sInit != NULL ) {

        if( ! sInit() ) {
            AppLog::info( "Steam: SteamAPI_Init failed -- Steam is probably "
                          "not running. Skipping Steam login." );
            closeLibrary();
            return false;
        }
    }
    else {
        // SteamErrMsg is a fixed 1024-byte buffer in the SDK.
        char errorMessage[1024];
        errorMessage[0] = '\0';

        if( sInitFlat( errorMessage ) != 0 ) {
            AppLog::infoF( "Steam: SteamAPI_InitFlat failed (%s). "
                           "Skipping Steam login.", errorMessage );
            closeLibrary();
            return false;
        }
    }

    sAPIStarted = true;

    void *steamClient = sCreateInterface( clientVersion );

    if( steamClient == NULL ) {
        AppLog::errorF( "Steam: the Steam client does not offer %s.",
                        clientVersion );
        steamAPI_shutdown();
        return false;
    }

    sSteamUser = sGetISteamUser( steamClient,
                                 sGetHSteamUser(), sGetHSteamPipe(),
                                 userVersion );

    if( sSteamUser == NULL ) {
        AppLog::errorF( "Steam: the Steam client does not offer %s.",
                        userVersion );
        steamAPI_shutdown();
        return false;
    }

    if( ! sBLoggedOn( sSteamUser ) ) {
        AppLog::info( "Steam: Steam is running but not logged in, "
                      "skipping Steam login." );
        steamAPI_shutdown();
        return false;
    }

    return true;
}



void steamAPI_shutdown() {
    if( sAPIStarted && sShutdown != NULL ) {
        sShutdown();
    }

    sAPIStarted = false;

    closeLibrary();
}



void steamAPI_runCallbacks() {
    if( sAPIStarted && sRunCallbacks != NULL ) {
        sRunCallbacks();
    }
}



unsigned long long steamAPI_getSteamID() {
    if( sSteamUser == NULL ) {
        return 0;
    }

    return sGetSteamID( sSteamUser );
}



unsigned int steamAPI_getAuthSessionTicket( unsigned char *outTicket,
                                            int inMaxLength ) {
    if( sSteamUser == NULL ) {
        return 0;
    }

    unsigned int ticketLength = 0;

    unsigned int handle = sGetAuthSessionTicket( sSteamUser, outTicket,
                                                 inMaxLength, &ticketLength,
                                                 NULL );

    if( handle == 0 || ticketLength == 0 ) {
        // Not necessarily a failure: Steam issues nothing while it is still
        // connecting. The caller decides how long to keep asking.
        return 0;
    }

    return ticketLength;
}
