// Generated by Claude (Anthropic).

#ifndef YUM_STEAM_CREDENTIALS_INCLUDED
#define YUM_STEAM_CREDENTIALS_INCLUDED

// Account setup through Steam, on demand.
//
// Vanilla OHOL does this in a separate program: Steam is told to run
// steamGateClient.exe, which proves to onehouronelife.com that this Steam
// user owns the game, receives an account, writes settings/email.ini and
// settings/accountKey.ini, and only then launches OneLife.exe. The mod is
// started directly by the player rather than by Steam, so that program never
// runs for us, and the mod has had to rely on the player launching vanilla
// through Steam at least once to leave those two files behind.
//
// This does the same exchange from inside the mod, so it does not matter who
// launched us or whether vanilla has ever run. Steam only has to be running
// and logged in.
//
// The protocol is minorGems/game/steamGate/server/protocol.txt, and the
// implementation follows steamGateClient.cpp so that the server sees exactly
// what it sees from a vanilla client.


// Fetches an account from the steamGate server and saves it into
// settings/email.ini and settings/accountKey.ini, replacing whatever was
// there.
//
// Driven by the GENERATE CREDS button on the settings page: nothing calls
// this on its own. Blocks the caller for a few seconds while Steam and the
// gate server talk, and returns false for every ordinary "no Steam here"
// situation, leaving the saved account untouched.
//
// Returns true if credentials were fetched and saved.
char fetchSteamCredentials();


#endif
