version: '3.8'

x-common: &common
  image: yummylife-buildscripts:latest
  build: .
  volumes:
    - ../:/app
  working_dir: /app
  restart: no

services:
  setup:
    <<: *common
    working_dir: /app/yummyLifeBuildScripts
    entrypoint: ["sh", "-c", "echo $(pwd) && sed 's/\r$//' ./setup-libs.sh | sh -s --"]
  build:
    <<: *common
    entrypoint: ["sh", "-c", "sed 's/\r$//' ./build-dev.sh | sh -s --"]
  build_windows:
    <<: *common
    entrypoint: ["sh", "-c", "sed 's/\r$//' ./build-dev.sh | sh -s -- windows"]
  build_linux:
    <<: *common
    entrypoint: ["sh", "-c", "sed 's/\r$//' ./build-dev.sh | sh -s -- linux"]
  shell:
    <<: *common
    command: ["/bin/bash"]
